on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  mine-cran-purls:
    runs-on: ubuntu-24.04
    name: Mine cran PackageURLs
    steps:
    - uses: aboutcode-org/scancode-action@beta
      with:
        scancodeio-repo-branch: "minecode-git-deployment#egg=scancodeio[mining]"
        pipelines: "mine_cran"
      env:
        FEDERATEDCODE_GIT_ACCOUNT_URL: https://github.com/aboutcode-data
        FEDERATEDCODE_GIT_SERVICE_TOKEN: ${{ secrets.MINING_GITHUB_TOKEN }}
        FEDERATEDCODE_GIT_SERVICE_NAME: "AboutCode Automation"
        FEDERATEDCODE_GIT_SERVICE_EMAIL: "automation@aboutcode.org"
