on: [workflow_dispatch]

jobs:
  mine-nuget-purls:
    runs-on: ubuntu-24.04
    name: Mine NuGet PackageURLs
    steps:
    - uses: aboutcode-org/scancode-action@beta
      with:
        scancodeio-repo-branch: "minecode-nuget-deployment#egg=scancodeio[mining]"
        pipelines: "mine_nuget"
      env:
        FEDERATEDCODE_GIT_ACCOUNT_URL: https://github.com/aboutcode-data
        FEDERATEDCODE_GIT_SERVICE_TOKEN: ${{ secrets.NUGET_MINING_GITHUB_TOKEN }}
        FEDERATEDCODE_GIT_SERVICE_NAME: "AboutCode Automation"
        FEDERATEDCODE_GIT_SERVICE_EMAIL: "automation@aboutcode.org"
