on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  mine-pypi-purls:
    runs-on: ubuntu-24.04
    name: Mine cargo PackageURLs
    steps:
    - uses: aboutcode-org/scancode-action@beta
      with:
        scancodeio-repo-branch: "minecode-git-deployment#egg=scancodeio[mining]"
        pipelines: "mine_cargo"
      env:
        FEDERATEDCODE_GIT_ACCOUNT_URL: https://github.com/aboutcode-data
        FEDERATEDCODE_GIT_SERVICE_TOKEN: ${{ secrets.MINING_GITHUB_TOKEN }}
        FEDERATEDCODE_GIT_SERVICE_NAME: "AboutCode Automation"
        FEDERATEDCODE_GIT_SERVICE_EMAIL: "automation@aboutcode.org"
